### ISSUE TITLE
[Suggestion] Promote Muninn/Graves to build a community around its improvement

### ISSUE THREAD

**Issue by Stephen-Gates** [muninn/graves#36]
I just came across [Linked Open Vocabularies (LOV)](https://lov.linkeddata.es/dataset/lov) and didn't find Muninn/Graves on it. I did find [The Muninn Military Ontology](https://lov.linkeddata.es/dataset/lov/vocabs/mil) on LOV.

My suggestion is to add Muninn/Graves to LOV, and other lists of quality vocabularies, to help build a broader community around the development and reuse of Muninn/Graves.

Sorry for adding this as an Issue but this repository doesn't have a [Discussion Forum](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions) which may be a better place for these types of suggestions. Alternatively, [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) could be used to categorise Issues but these must be applied by project maintainers.

**Comment by rwarren2** [comment]
Stephen,

Agreed. Linked Open Vocabularies (LOV) has been around for a while, the issue is that their internal parser is temperamental and they have limited resources to dedicate to it. I'll try and resubmit as soon as v1.5 is done and see if it parses properly.  

Your point about building community is taken; but it is a small community. You should now be able to change labels in the project.
